# Generated by Django 5.1.4 on 2024-12-17 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Afp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
                ('Porcentaje_Descuento', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoPermiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Sistema_de_salud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
                ('Porcentaje_Descuento', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('Nombre', models.CharField(max_length=30)),
                ('Apellido', models.CharField(max_length=20)),
                ('Rut', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('Sexo', models.CharField(max_length=20)),
                ('Contraseña', models.CharField(max_length=50)),
                ('Imagen', models.ImageField(upload_to='Trabajadores')),
                ('Fecha_ingreso', models.DateField(auto_now_add=True)),
                ('Correo', models.EmailField(max_length=254)),
                ('Telefono', models.CharField(max_length=9)),
                ('Direccion', models.CharField(max_length=100)),
                ('Salario', models.IntegerField()),
                ('AFP', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infoEmpleadosApp.afp')),
                ('Cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infoEmpleadosApp.cargo')),
                ('Sistema_de_salud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infoEmpleadosApp.sistema_de_salud')),
            ],
        ),
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha_de_inicio', models.DateField()),
                ('Fecha_de_solicitud', models.DateField(auto_now_add=True)),
                ('Cantidad_de_dias', models.IntegerField()),
                ('Motivo', models.CharField(max_length=100)),
                ('EstadoPermiso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infoEmpleadosApp.estadopermiso')),
                ('Trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infoEmpleadosApp.trabajador')),
            ],
        ),
        migrations.CreateModel(
            name='Liquidacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha', models.DateField(auto_now_add=True)),
                ('Sueldo_Liquido', models.IntegerField()),
                ('Descuento_Afp', models.IntegerField()),
                ('Descuento_Salud', models.IntegerField()),
                ('Trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infoEmpleadosApp.trabajador')),
            ],
        ),
    ]
